channels:
  - defaults
  - conda-forge
dependencies:
    - python=3.7.12
    - pip=21.3.1
    - setuptools=60.5
    - jupyterlab=3.2.8
    - numpy=1.20.1
    - scipy=1.6.0
    - pandas=1.2.2
    - matplotlib=3.3.4
    - seaborn=0.11.1
    - ipython==7.31.1
    - pip:
      - jupyterlab_latex
