channels:
    - conda-forge
dependencies:
    - python
    - pip
    - setuptools
    - jupyterlab
    - numpy=1.20.1
    - scipy=1.6.0
    - pandas=1.2.2
    - matplotlib=3.3.4
    - seaborn=0.11.1
    - ipython==7.20.0
    - pip:
      - jupyterlab_latex
